### ISSUE TITLE
TYPO3 7.6 und TER

### ISSUE THREAD

**Issue by Schweriner** [teamgeist/tgm_seo#1]
Die Extension muss auf Ihre 7.6 kompat. geprüft werden und ins TER. Die pages Overrides der ext_tables.php sollten in den Ordner Configuration/Overrides ausgelagert werden.

**Comment by Xippo** [comment]
7.6 kompat:
92bbc4a1d80d8bd28aa369103bf4fbc393e86a57

**Comment by s-thierock** [comment]
81a5b6ea8b1590546f14e67b5ba881c46fcc5911
